skills:
  dungeoneering:
    name: "Dungeoneering" # Name to be displayed
    description: "Complete dungeons to earn XP" #
    material: "skeleton_skull" # material to be used in the menu
    pos: "4,4" # position in the menu

stats:
  mythic_dungeon_loot_bonus:
    name: "Dungeon Loot Bonus"
    description: "How much extra loot you gain inside dungeons."
    color: "<yellow>"
    symbol: "🪙"
    material: "gold_ingot"
  mythic_boss_attack_bonus:
    name: "Boss Attack Bonus"
    description: "How much extra damage you do to bosses."
    color: "<red>"
    symbol: "💀⚔"
    material: "redstone_block"
  mythic_boss_defense_bonus:
    name: "Boss Defense Bonus"
    description: "How much extra damage you can take from bosses."
    color: "<blue>"
    symbol: "💀🛡"
    material: "diamond_block"
  mythic_mob_defense_bonus:
    name: "Mob Defense Bonus"
    description: "How much extra damage you can take from mobs."
    color: "<blue>"
    symbol: "🛡"
    material: "diamond"
  mythic_mob_attack_bonus:
    name: "Mob Attack Bonus"
    description: "How much extra damage you do to mobs"
    color: "<red>"
    symbol: "⚔"
    material: "redstone"

traits:
  mythic_dungeon_loot_bonus:
    name: "Mythic Dungeon Loot Bonus"
  mythic_boss_attack_bonus:
    name: "Boss Attack Bonus"
  mythic_boss_defense_bonus:
    name: "Boss Defense Bonus"
  mythic_mob_defense_bonus:
    name: "Mob Defense Bonus"
  mythic_mob_attack_bonus:
    name: "Mob Attack Bonus"

weekdays_xp_multiplier:
  monday: 1
  tuesday: 1
  wednesday: 1
  thursday: 1
  friday: 1
  saturday: 2
  sunday: 2

bosses:
  - "SkeletalKnight"

loottables:
  SkeletalKnight: "Bonnn"